# Generated by Django 5.2.5 on 2026-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('allure', 'Allure')], default='allure', max_length=32)),
                ('report_path', models.CharField(blank=True, max_length=1024)),
                ('report_url', models.CharField(blank=True, max_length=1024)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='executions.testexecution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
