# Generated by Django 5.2.5 on 2026-04-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('azure', 'Azure'), ('other', 'Other')], max_length=64)),
                ('model_name', models.CharField(max_length=128)),
                ('api_base', models.URLField(blank=True, max_length=512)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('template_text', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scene', '-version'],
            },
        ),
    ]
