# Generated by Django 5.2.5 on 2026-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('json', 'JSON')], max_length=32)),
                ('raw_content', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_schemas', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=16)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('request_schema', models.JSONField(blank=True, default=dict)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_testing.apischema')),
            ],
            options={
                'ordering': ['path', 'method'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=dict)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_testing.apiendpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_cases', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiTestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_test_suites', to='projects.project')),
                ('test_cases', models.ManyToManyField(blank=True, related_name='api_suites', to='api_testing.apitestcase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
