# Generated by Django 5.2.5 on 2026-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('api_suite', 'API suite'), ('web_suite', 'Web suite')], max_length=32)),
                ('target_id', models.PositiveBigIntegerField()),
                ('cron_expr', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
