# Generated by Django 5.2.5 on 2026-04-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_type', models.CharField(choices=[('api', 'API'), ('web', 'Web')], max_length=16)),
                ('target_type', models.CharField(choices=[('case', 'Case'), ('suite', 'Suite')], max_length=16)),
                ('target_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('trigger_source', models.CharField(choices=[('manual', 'Manual'), ('scheduler', 'Scheduler')], default='manual', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('log_path', models.CharField(blank=True, max_length=1024)),
                ('artifact_path', models.CharField(blank=True, max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='executions.testexecution')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
